require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TBear' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  # pod 'RNReactNativeLocalBarcodeRecognizer', :path => '../node_modules/react-native-local-barcode-recognizer'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  # pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RealmJS', :path => '../node_modules/realm'

  target 'TBearTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'TBear-tvOS' do
  # Pods for TBear-tvOS

  target 'TBear-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
  end
end
